# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - prometheus--dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5925b4dafd9942119dfa83b083f9f7c3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ec3ccf40622a4f99b1f815df39cf9565 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5925b4dafd9942119dfa83b083f9f7c3 }}/ubuntu/prometheus:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'prometheus--dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fc88d6fd4879437a8d69a4f96cbf986f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5925b4dafd9942119dfa83b083f9f7c3 }}/ubuntu/prometheus:${{ github.sha }}'